name: CI Tests

on: [pull_request,push]

jobs:
  Ubuntu:

    runs-on: ubuntu-20.04

    name: Ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install prerequisties
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            qtbase5-dev \
            libqt5svg5-dev \
            qttools5-dev

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake ..

      - name: Building
        run: |
          make -j$(nproc) -C build

  MSVC:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        qt_ver: [5.12.10, 5.15.2]

    name: MSVC_Qt_${{ matrix.qt_ver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-${{ matrix.qt_ver }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configuring
        run: |
          mkdir build; cd build
          cmake ..

      - uses: microsoft/setup-msbuild@v1.0.2
      - name: Building
        run: |
          MSBuild -maxCpuCount build\qwt5-qt5.sln

  MinGW-w64:

    runs-on: windows-latest

    name: MinGW-w64

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install MinGW-w64 packages
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-qt5

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake .. -G"MSYS Makefiles"

      - name: Building
        run: |
          make -C build -j$(nproc)
